[build]
  base = "frontend"
  command = "npm run build"
  publish = ".output/public"
  functions = ".output/server/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200