[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = ".output/public"

[functions]
  directory = ".output/server/functions"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
