[build]
  base = "frontend"
  command = "npm install && npm run generate"  # For static
  publish = "frontend/dist"

[functions]
  directory = ".output/server/functions"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
